# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Plugings
plugins:
  - jekyll-paginate

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            Aditya Sathish
tagline:          Adeeteeyaas
description:      My landing page, portfolio and thought vault on the internet
url:              https://adeeeteeyaa.github.io
baseurl:          "/"

author:
  name:           'Aditya Sathis(h)'
  url:            https://adeeeteeyaa.github.io

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/adeeteeyaa/adeeteeyaa.github.io

career_start:     "2017-08-23"