# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Aditya Sathish
tagline:          Adeeteeyaa
description:      My landing page, portfolio and thought vault on the internet
url:              https://adeeeteeyaa.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adeeteeyaa/adeeteeyaa.github.io